# Generated by Django 4.2.2 on 2023-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0006_city_alter_restaurant_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
    ]
